dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install pytest
  - pip install .
script:
  - pytest
addons:
  apt:
    packages:
      - gfortran
branches:
  only:
    - master
