#!/bin/bash
set -eu

# .env cleanup
sort .env | uniq - .env.new
rm .env && mv .env.new .env

# IPython startup
cat << EOS > $IPYTHONDIR/profile_default/startup/00.py
import numpy as np
import xarray as xr
import pandas as pd
import ndradex as nd
EOS

# IPython config
cat << EOS > $IPYTHONDIR/profile_default/ipython_config.py
c.InteractiveShellApp.exec_lines = ['%autoreload 2']
c.InteractiveShellApp.extensions = ['autoreload']
EOS

# Jupyter themes
jt -t grade3 -cellw 97% -f source -nf sourcesans -tf sourcesans
