#!/bin/bash -eu


# Install package dependencies with Pipenv
if ! type pipenv >/dev/null 2>&1
then
    echo "Pipenv is not installed"
    exit 1
fi

pipenv install --dev


# Install IPython kernel to Jupyter
pipenv run python -m ipykernel install \
    --user \
    --name "python-$(basename $PWD)" \
    --display-name "Python ($(basename $PWD))"


# Setup VS Code's workspace settings
if type code >/dev/null 2>&1
then
    code --install-extension ms-python.python
fi

mkdir -p .vscode
cat << EOS > .vscode/settings.json
{
    "editor.formatOnSave": true,
    "python.formatting.provider": "black",
    "python.linting.enabled": true,
    "python.linting.lintOnSave": true,
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": false,
    "python.pythonPath": "$(pipenv run which python)",
}
EOS
