name: PyPI

on:
  release:
    types:
      - created

jobs:
  job:
    name: PyPI
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:python3.12-bookworm
    env:
      UV_PROJECT_ENVIRONMENT: /usr/local
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: uv build && uv publish
