name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job:
    name: Test (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install project dependencies
        run: |
          sudo apt install gfortran
          pip install poetry
          poetry install
          cd ndradex/bin
          make build
      - name: Test code's formatting (Black)
        run: black --check ndradex tests
      - name: Test code's execution (pytest)
        run: pytest -v tests
